server:
  port: 8081
spring:
  application:
    name: http
  security:
    user:
      name: admin
      password: admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
arthas:
  tunnel-server: ws://192.168.50.83:7777/ws
  agent-id: hsehdfsfghhwertyfad